---
- name: Converge
  hosts: all
  gather_facts: true
  connection: community.okd.oc
  tasks:
    - name: "Include backup_file"
      ansible.builtin.include_role:
        name: "sample_namespace.sample_collection.backup_file"
