---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:

    - name: Get stats of a file
      ansible.builtin.stat:
        path: /etc/hosts
      register: st
    - name: Fail if the file does not belong to 'root'
      ansible.builtin.fail:
        msg: "Whoops! file ownership has changed"
      when: st.stat.pw_name != 'root'
      
