---
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
    ansible_connection_options:
      connection: local
platforms:
  - name: molecule-ubi8-init-1
    image: registry.access.redhat.com/ubi8/ubi-init@sha256:75cb1eb60b9636f8daa584c231db552c1de94006778e7224643804a696f04fad
    workingDir: '/tmp'
provisioner:
  name: ansible
  # Failing to write the ansible into /.ansible/tmp
  config_options:
    defaults:
      remote_tmp: '/tmp'
      # This just says go back a directory and thats your roles path
      # You can also provide this via pipeline with something like this
      # ANSIBLE_ROLES_PATH: $COLLECTION_ROLES

      # COLLECTIONS_PATH: ${PROJECT_SOURCE}
      # ANSIBLE_ROLES_PATH: ${PROJECT_SOURCE}/${backup_file_molecule_namespace}
  inventory:
    group_vars:
      all:
        backup_file_molecule_namespace: ${DEVWORKSPACE_NAMESPACE}
        backup_file_molecule_pip_dependencies:
          - kubernetes
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
