---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:

    - name: Store user ENVs
      ansible.builtin.set_fact:
        molecule_user_home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
        molecule_user_path: "{{ lookup('ansible.builtin.env', 'PATH') }}"
